<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        * {
            padding: 0;
            margin: 0;
        }
        header {
            padding: 20px;
            text-align: center;
            background-color: black;
            color: gold;
        }

        .main {
            width: 80vw;
            margin: 0 auto;
            background-color: #cbcaca;
        }
    </style>
</head>
<body>
    <header>
        <h1>Документъ</h1>
    </header>
<div class="main">
    <div>
        fgdfgf
    </div>

</div>
</body>
</html>